openapi: 3.0.1
info:
  title: OpenPAI Protocol
  description: OpenPAI Job Specification
  license:
    name: MIT License
    url: 'https://github.com/microsoft/pai/blob/master/LICENSE'
  version: 2.0.0
components:
  schemas:
    JobProtocol:
      type: object
      description: openpai job protocol
      properties:
        protocolVersion:
          type: string
          description: Protocol version, current version is 2.
        name:
          type: string
          maxLength: 255
          description: String in ^[a-zA-Z0-9_-]+$ format, no longer than 255 characters.
        type:
          type: string
          description: Component type, should be "job" here.
        version:
          type: string
          description: Component version, default is latest.
        contributor:
          type: string
        description:
          type: string
        prerequisites:
          type: array
          items:
            type: object
            properties:
              name:
                type: string
              type:
                type: string
                enum:
                  - data
                  - script
                  - dockerimage
                  - output
              version:
                type: string
              contributor:
                type: string
              description:
                type: string
              auth:
                type: object
                properties:
                  username:
                    type: string
                  password:
                    type: string
                  registryuri:
                    type: string
              uri:
                oneOf:
                  - type: string
                  - type: array
                    items:
                      type: string
        parameters:
          type: object
          additionalProperties: true
        secrets:
          type: object
          additionalProperties: true
        jobRetryCount:
          type: integer
          description: Default is 0.
        taskRoles:
          type: object
          additionalProperties:
            type: object
            properties:
              instances:
                type: integer
                description: Default is 1, instances of a taskRole, no less than 1.
              completion:
                type: object
                description: Completion poclicy for the job.
                properties:
                  minFailedInstances:
                    type: integer
                  minSucceededInstances:
                    type: integer
              taskRetryCount:
                type: integer
                description: Default is 0.
              dockerImage:
                type: string
                description: Should reference to a dockerimage defined in prerequisites.
              data:
                type: string
              output:
                type: string
              script:
                type: string
              extraContainerOptions:
                type: object
                properties:
                  shmMB:
                    type: integer
                    description: Config the /dev/shm in a docker container.
                  infiniband:
                    type: boolean
                    description: Use InfiniBand devices or not in a docker container.
              resourcePerInstance:
                type: object
                properties:
                  cpu:
                    type: integer
                    description: CPU number, unit is CPU vcore.
                  memoryMB:
                    type: integer
                    description: Memory number, unit is MB.
                  gpu:
                    type: integer
                    description: GPU number, unit is GPU card.
                  ports:
                    type: object
                    additionalProperties:
                      type: integer
                      description: Port number for the port label.
              commands:
                type: array
                items:
                  type: string
            required:
              - dockerImage
              - resourcePerInstance
              - commands
        deployments:
          type: array
          items:
            type: object
            properties:
              name:
                type: string
              taskRoles:
                type: object
                additionalProperties:
                  type: object
                  properties:
                    preCommands:
                      type: array
                      items:
                        type: string
                    postCommands:
                      type: array
                      items:
                        type: string
        defaults:
          type: object
          description: Default cluster specific settings.
          properties:
            virtualCluster:
              type: string
            deployment:
              type: string
        extras:
          type: object
          description: Extra field, save any information that plugin may use.
          properties:
            submitFrom:
              type: string
            hivedscheduler:
              type: object
              properties:
                jobPriorityClass:
                  type: string
                taskRoles:
                  type: object
                  additionalProperties:
                    type: object
                    properties:
                      gpuType:
                        type: string
                      reservationId:
                        type: string
                      affinityGroupName:
                        type: string
      required:
        - protocolVersion
        - name
        - type
        - taskRoles
